src/main/java/inscricao/entity/Candidato.java
package inscricao.entity;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 *
 * @author Wilson
 */
public class Candidato implements Serializable {
    private static final long serialVersionUID = 1L;
    private Long cpf;
    private String rg;
    private String nome;
    private String instituicao;
    private String programa;
    private String endereco;
    private String bairro;
    private String cidade;
    private String estado;
    private Integer cep;
    private String fone;
    private String celular;
    private String email;
    private Idioma idioma;
    private Date dataHora;

    public Candidato() {
    }

    public Candidato(Idioma idioma) {
        this.idioma = idioma;
    }

    public Candidato(Long cpf) {
        this.cpf = cpf;
    }

    public Long getCpf() {
        return cpf;
    }

    public void setCpf(Long cpf) {
        this.cpf = cpf;
    }

    public String getRg() {
        return rg;
    }

    public void setRg(String rg) {
        this.rg = rg;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getInstituicao() {
        return instituicao;
    }

    public void setInstituicao(String instituicao) {
        this.instituicao = instituicao;
    }

    public String getPrograma() {
        return programa;
    }

    public void setPrograma(String programa) {
        this.programa = programa;
    }

    public String getEndereco() {
        return endereco;
    }

    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    public String getBairro() {
        return bairro;
    }

    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    public String getCidade() {
        return cidade;
    }

    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public Integer getCep() {
        return cep;
    }

    public void setCep(Integer cep) {
        this.cep = cep;
    }

    public String getFone() {
        return fone;
    }

    public void setFone(String fone) {
        this.fone = fone;
    }

    public String getCelular() {
        return celular;
    }

    public void setCelular(String celular) {
        this.celular = celular;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Idioma getIdioma() {
        return idioma;
    }

    public void setIdioma(Idioma idioma) {
        this.idioma = idioma;
    }

    public Date getDataHora() {
        return dataHora;
    }

    public void setDataHora(Date dataHora) {
        this.dataHora = dataHora;
    }

}

src/main/java/inscricao/entity/Idioma.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package inscricao.entity;

import java.io.Serializable;

/**
 *
 * @author Wilson
 */
public class Idioma implements Serializable {
    private Integer codigo;
    private String descricao;

    public Idioma() {
    }

    public Idioma(Integer codigo) {
        this.codigo = codigo;
    }

    public Idioma(Integer codigo, String descricao) {
        this.codigo = codigo;
        this.descricao = descricao;
    }

    public Integer getCodigo() {
        return codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

}

src/main/java/inscricao/faces/mngbeans/InscricaoBean.java
package inscricao.faces.mngbeans;

import inscricao.entity.Candidato;
import inscricao.entity.Idioma;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.enterprise.context.RequestScoped;
import javax.faces.model.ArrayDataModel;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import javax.inject.Inject;
import javax.inject.Named;
import utfpr.faces.support.PageBean;

/**
 *
 * @author Wilson
 */
@Named
@RequestScoped
public class InscricaoBean extends PageBean {
    
    @Inject
    private RegistroBean candidatosList;
    
    private DataModel<Candidato> candidadtosListDataModel;
    
    private static final Idioma[] IDIOMAS = {
        new Idioma(1, "Inglês"),
        new Idioma(2, "Alemão"),
        new Idioma(3, "Francês")
    };
    
    private Candidato candidato = new Candidato(IDIOMAS[0]); // inicialmente ingles
    private List<SelectItem> idiomaItemList;
    private ArrayDataModel<Idioma> idiomasDataModel;

    public Candidato getCandidato() {
        return candidato;
    }

    public void setCandidato(Candidato candidato) {
        this.candidato = candidato;
    }

    public Idioma[] getIdiomas() {
        return IDIOMAS;
    }
    
    public List<SelectItem> getIdiomaItemList() {
        if (idiomaItemList != null) return idiomaItemList;
        idiomaItemList = new ArrayList<>();
        for (Idioma id: IDIOMAS) {
            idiomaItemList.add(new SelectItem(id.getCodigo(), id.getDescricao()));
        }
        return idiomaItemList;
    }
    
    public ArrayDataModel<Idioma> getIdiomasDataModel() {
        if (idiomasDataModel == null) {
            idiomasDataModel = new ArrayDataModel<>(IDIOMAS);
        }
        return idiomasDataModel;
    }

    public RegistroBean getCandidatosList() {
        return candidatosList;
    }

    public void setCandidatosList(RegistroBean candidatos) {
        this.candidatosList = candidatos;
    }
    
    public String confirmaAction() {
        candidato.setDataHora(new Date());
        candidato.setIdioma(IDIOMAS[candidato.getIdioma().getCodigo()-1]);
        candidatosList.addCandidatosList(candidato);
        
        return "confirma";
    }
    
    public DataModel<Candidato> getCandidatosListDataModel() {
        candidadtosListDataModel = new ListDataModel<>(candidatosList.getCandidatosList());
        return candidadtosListDataModel;
    }
    
    public String candidatoAction(){
        setCandidato(candidadtosListDataModel.getRowData());
        candidatosList.getCandidatosList().remove(candidadtosListDataModel.getRowData());
        return "inscricao";
    }
    
    public void excluiAction(){
        candidatosList.getCandidatosList().remove(candidadtosListDataModel.getRowData());
    }
}

src/main/java/inscricao/faces/mngbeans/RegistroBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inscricao.faces.mngbeans;

import inscricao.entity.Candidato;
import java.util.ArrayList;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;
import utfpr.faces.support.PageBean;
/**
 *
 * @author andre
 */
@Named
@ApplicationScoped
public class RegistroBean extends PageBean{
    private ArrayList<Candidato> CandidatosList = new ArrayList<>();

    public ArrayList<Candidato> getCandidatosList() {
        return CandidatosList;
    }

    public void addCandidatosList(Candidato candidato) {
        this.CandidatosList.add(candidato);
    }
    
    
}

src/main/java/inscricao/login/LoginBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inscricao.login;

import java.io.Serializable;
import javax.enterprise.context.RequestScoped;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;


@Named
@SessionScoped
public class LoginBean implements Serializable {
    private String login;
    private String senha;

    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }
    
    public String login(){
        if(this.login.equals(this.senha))
            return "inscricao";
        
        return "login";
    }
    
}

src/main/java/utfpr/faces/support/ApplicationBean.java
/*
 * EXEMPLOS
 */
package utfpr.faces.support;


/**
 * O bean de aplicação
 * @author Wilson
 */
public class ApplicationBean extends FacesBean {
}

src/main/java/utfpr/faces/support/FacesBean.java
/*
 * === CLASSES DE APOIO JSF ===
 * Este código fonte pode ser livremente copiado, modificado e distribuído,
 * desde que esta mensagem seja preservada.
 * Todo o esforço foi feito para escrever um código correto e eficiente, entretanto o
 * autor não assume qualquer responsabilidade, direta ou indireta sobre a aplicabilidade
 * e/ou adequação a um fim específico e não garante que esteja livre de erros.
 * Copyright (C) 2009 <a href="http://www.utfpr.edu.br">Universidade Tecnológica Federal do Paraná</a>
 */

package utfpr.faces.support;

import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.servlet.ServletContext;
import javax.servlet.http.HttpSession;

/**
 * Classe base para os beans de aplicação, sessão, request e página.
 * @version 1.0.0
 *
 * @author Wilson Horstmeyer Bogado <wilson@utfpr.edu.br>
 * <a href="http://www.utfpr.edu.br">Universidade Tecnológica Federal do Paraná</a>
 */
public class FacesBean implements Serializable {

    private static final Logger logger = Logger.getLogger(PageBean.class.getName());

    /**
     * Retorna o <code>FacesContext</code> corrente.
     * @return O <code>FacesContext</code>
     */
    public FacesContext getFacesContext() {
        return FacesContext.getCurrentInstance();
    }

    /**
     * Retorna o contexto externo de JSF.
     * @return O contexto externo
     */
    public ExternalContext getExternalContext() {
        return getFacesContext().getExternalContext();
    }
    
    /**
     * Retorna ou cria uma sessão. 
     * @param create {@code true} para cria uma nova sessão, caso não exista
     * @return A sessão, ou null, caso não exista
     */
    public HttpSession getSession(boolean create) {
        return (HttpSession) getExternalContext().getSession(create);
    }
    
    /**
     * Retorna a sessão atual ou {@code null} caso não exista.
     * @return A sessão existente ou {@code null}
     */
    public HttpSession getSession() {
        return getSession(false);
    }
    
    /**
     * Retorna o contexto do servlet.
     * @return O contexto do servlet
     */
    public ServletContext getServletContext() {
        return (ServletContext) getExternalContext().getContext();
    }

    /**
     * Gera um log de informação com a mensagem especificada.
     * @param message A mensagem
     */
    public void log(String message) {
        logger.log(Level.INFO, message);
    }

    /**
     * Gera um log de erro com a mensagem e exceção especificadas.
     * @param message A mensagem
     * @param t A exceção
     */
    public void log(String message, Throwable t) {
        logger.log(Level.SEVERE, message, t);
    }
}

src/main/java/utfpr/faces/support/PageBean.java
/*
 * EXEMPLOS
 */
package utfpr.faces.support;

import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;

/**
 * Classe base dos managed beans de páginas JSF.
 * @author Wilson
 */
public class PageBean extends FacesBean {

    /**
     * Retorna um managed bean dado o seu nome
     * @return O bean de aplicação
     */
    public Object getBean(String name) {
        return getFacesContext().getApplication().evaluateExpressionGet(
            FacesContext.getCurrentInstance(), "#{" + name +  "}", Object.class);
    }

    /**
     * Gera uma mensagem de informação associada a um componente.
     * @param component O componente
     * @param message A mensagem
     */
    public void info(UIComponent component, String message) {
        getFacesContext().addMessage(component.getClientId(getFacesContext()),
            new FacesMessage(FacesMessage.SEVERITY_INFO, message, null));
    }

    /**
     * Gera uma mensagem de informação não associada a um componente.
     * @param message O <i>summary</i> da mensagem
     */
    public void info(String message) {
        getFacesContext().addMessage(null,
            new FacesMessage(FacesMessage.SEVERITY_INFO, message, null));
    }

    /**
     * Gera uma mensagem de advertência associada a um componente.
     * @param component O componente
     * @param message A mensagem
     */
    public void warn(UIComponent component, String message) {
        getFacesContext().addMessage(component.getClientId(getFacesContext()),
            new FacesMessage(FacesMessage.SEVERITY_WARN, message, null));
    }

    /**
     * Gera uma mensagem de advertência não associada a um componente.
     * @param message O <i>summary</i> da mensagem
     */
    public void warn(String message) {
        getFacesContext().addMessage(null,
            new FacesMessage(FacesMessage.SEVERITY_WARN, message, null));
    }

    /**
     * Gera uma mensagem de erro associada a um componente.
     * @param component O componente
     * @param message A mensagem
     */
    public void error(UIComponent component, String message) {
        getFacesContext().addMessage(component.getClientId(getFacesContext()),
            new FacesMessage(FacesMessage.SEVERITY_ERROR, message, null));
    }

    /**
     * Gera uma mensagem de erro não associada a um componente.
     * @param message <i>summary</i> da mensagem
     */
    public void error(String message) {
        getFacesContext().addMessage(null,
            new FacesMessage(FacesMessage.SEVERITY_ERROR, message, null));
    }
}

src/main/java/utfpr/faces/support/RequestBean.java
/*
 * === CLASSES DE APOIO JSF ===
 * Este código fonte pode ser livremente copiado, modificado e distribuído,
 * desde que esta mensagem seja preservada.
 * Todo o esforço foi feito para escrever um código correto e eficiente, entretanto o
 * autor não assume qualquer responsabilidade, direta ou indireta sobre a aplicabilidade
 * e/ou adequação a um fim específico e não garante que esteja livre de erros.
 * Copyright (C) 2009 <a href="http://www.utfpr.edu.br">Universidade Tecnológica Federal do Paraná</a>
 */

package utfpr.faces.support;

/**
 * Classe base para os beans de request.
 * @version 1.0.0
 *
 * @author Wilson Horstmeyer Bogado <wilson@dainf.ct.utfpr.edu.br>
 * <a href="http://www.utfpr.edu.br">Universidade Tecnológica Federal do Paraná</a>
 */
public class RequestBean extends PageBean {

}

src/main/java/utfpr/faces/support/SessionBean.java
/*
 * === CLASSES DE APOIO JSF ===
 * Este código fonte pode ser livremente copiado, modificado e distribuído,
 * desde que esta mensagem seja preservada.
 * Todo o esforço foi feito para escrever um código correto e eficiente, entretanto o
 * autor não assume qualquer responsabilidade, direta ou indireta sobre a aplicabilidade
 * e/ou adequação a um fim específico e não garante que esteja livre de erros.
 * Copyright (C) 2009 <a href="http://www.utfpr.edu.br">Universidade Tecnológica Federal do Paraná</a>
 */
package utfpr.faces.support;

/**
 * Classe base par o bean de sessão.
 * @version 1.0.0
 *
 * @author Wilson Horstmeyer Bogado <wilson@dainf.ct.utfpr.edu.br>
 * <a href="http://www.utfpr.edu.br">Universidade Tecnológica Federal do Paraná</a>
 */
public class SessionBean extends PageBean {
}

src/main/webapp/candidatos.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                template="/WEB-INF/templates/layout.xhtml">

    <ui:define name="styles">
        <link href="#{request.contextPath}/css/inscricao.css" rel="stylesheet" type="text/css" />
    </ui:define>

    <ui:define name="metadata">
    </ui:define>

    <ui:define name="javascript">
    </ui:define>

    <ui:define name="content">
        <h:form>
        <h:dataTable border="1" value="#{inscricaoBean.candidatosListDataModel}" var="cand">
            <h:column>
                <f:facet name="header">
                    <h:outputText value="CPF" />
                </f:facet>
                <h:outputText id="cpf" value="#{cand.cpf}" converter="cpfConverter"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    <h:outputText value="Nome" />
                </f:facet>
                <h:commandLink action="#{inscricaoBean.candidatoAction}">
                    <h:outputText id="nome" value="#{cand.nome}"/>
                </h:commandLink>
            </h:column>
            <h:column>
                <f:facet name="header">
                    <h:outputText value="Cidade" />
                </f:facet>
                <h:outputText id="cidade" value="#{cand.cidade}"/>
            </h:column>
            <h:column>
                <f:facet name="header">
                    <h:outputText value="Estado" />
                </f:facet>
                <h:outputText id="estado" value="#{cand.estado}"/>
            </h:column>
            <h:column>
                <h:commandButton type="input" action="#{inscricaoBean.excluiAction}" value="Excluir"/>
            </h:column>
        </h:dataTable>
        </h:form>
    </ui:define>

</ui:composition>

src/main/webapp/confirma.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                template="/WEB-INF/templates/layout.xhtml">

    <ui:define name="styles">
        <link href="#{request.contextPath}/css/inscricao.css" rel="stylesheet" type="text/css" />
    </ui:define>

    <ui:define name="metadata">
    </ui:define>

    <ui:define name="javascript">
    </ui:define>

    <ui:define name="content">
        <h:form>
            <h:panelGroup styleClass="titulo-form form-block" layout="block">
                <h:outputText id="title" value="INSCRIÇÃO CONFIRMADA"/>
            </h:panelGroup>
            <h:panelGroup styleClass="form-block" layout="block">
                <h:outputText id="nome" value="Prezado(a) #{inscricaoBean.candidato.nome},"/>
            </h:panelGroup>
            <h:panelGroup styleClass="form-block" layout="block">
                <h:outputText id="useless" value="Seguem os dados da sua inscrição"/>
            </h:panelGroup>
            <h:panelGroup styleClass="form-block" layout="block">
                <h:outputLabel for="idioma" value="Idioma"/>
                <h:outputText id="idioma" value="#{inscricaoBean.candidato.idioma.descricao}"/>
            </h:panelGroup>
            <h:panelGroup styleClass="form-block" layout="block">
                <h:outputLabel for="cpf" value="CPF"/>
                <h:outputText id="cpf" value="#{inscricaoBean.candidato.cpf}" converter="cpfConverter"/>
            </h:panelGroup>
            <h:panelGroup styleClass="form-block" layout="block">
                <h:outputLabel for="end" value="Enderço"/>
                <h:outputText id="end" value="#{inscricaoBean.candidato.endereco}"/>
            </h:panelGroup>
            <h:panelGroup styleClass="form-block" layout="block">
                <h:outputLabel for="dataHora" value="Data e hora"/>
                <h:outputText id="dataHora" value="#{inscricaoBean.candidato.dataHora}">
                    <f:convertDateTime dateStyle="full" locale="pt_BR"/>
                </h:outputText><br/>
            </h:panelGroup>
            <h:panelGroup styleClass="form-block submit" layout="block">
                <h:commandButton value="Voltar" action="inscricao"/>
            </h:panelGroup>
            <h:messages/>
        </h:form>
    </ui:define>

</ui:composition>

src/main/webapp/idiomas.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                template="/WEB-INF/templates/layout.xhtml">

    <ui:define name="styles">
        <link href="#{request.contextPath}/css/inscricao.css" rel="stylesheet" type="text/css" />
    </ui:define>

    <ui:define name="metadata">
    </ui:define>

    <ui:define name="javascript">
    </ui:define>

    <ui:define name="content">
        <h:form>
           <div class="titulo-form">CADASTRO DE IDIOMAS</div>
           <h:dataTable value="#{inscricaoBean.idiomasDataModel}" var="i"
                        border="1" rules="all" cellpadding="4">
               <h:column>
                   <f:facet name="header">
                       <h:outputText value="Código"/>
                   </f:facet>
                   <h:outputText value="#{i.codigo}"/>
               </h:column>
               <h:column>
                   <f:facet name="header">
                       <h:outputText value="Descriçao"/>
                   </f:facet>
                   <h:outputText value="#{i.descricao}"/>
               </h:column>
           </h:dataTable>
            <h:messages/>
        </h:form>
    </ui:define>

</ui:composition>

src/main/webapp/inscricao.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                template="/WEB-INF/templates/layout.xhtml">

    <ui:define name="styles">
        <link href="#{request.contextPath}/css/inscricao.css" rel="stylesheet" type="text/css" />
    </ui:define>

    <ui:define name="metadata">
    </ui:define>

    <ui:define name="javascript">
    </ui:define>

    <ui:define name="content">
        <h:form>
            <div class="titulo-form">FICHA DE INSCRIÇÃO</div>
            <h:panelGroup style="text-align: left; margin-bottom: 10px;" layout="block">
                <h:panelGroup styleClass="form-block" layout="block">
                    <h:outputLabel for="idioma" value="Idioma"/>
                    <h:selectOneMenu id="idioma" value="#{inscricaoBean.candidato.idioma.codigo}" style="width:12em">
                        <f:selectItems value="#{inscricaoBean.idiomas}" var="i" itemValue="#{i.codigo}" itemLabel="#{i.descricao}"/>
                    </h:selectOneMenu>
                </h:panelGroup>
                <h:panelGroup styleClass="form-block" layout="block">
                    <h:outputLabel for="cpf" value="CPF" styleClass="requerido"/>
                    <h:inputText id="cpf" value="#{inscricaoBean.candidato.cpf}" label="CPF" size="15" maxlength="14" required="true" converter="cpfConverter">
                        <f:validator validatorId="cpfValidator"/>
                    </h:inputText>
                    <h:outputLabel for="rg" value="RG" styleClass="requerido"/>
                    <h:inputText id="rg" value="#{inscricaoBean.candidato.rg}" size="25" label="RG" maxlength="20" required="true"/>
                </h:panelGroup>
                <h:panelGroup styleClass="form-block" layout="block">
                    <h:outputLabel for="nome" value="Nome" styleClass="requerido"/>
                    <h:inputText id="nome" value="#{inscricaoBean.candidato.nome}" size="50"
                         label="Nome" maxlength="100" required="true"/>
                </h:panelGroup>
                <h:panelGroup styleClass="form-block" layout="block">
                    <h:outputLabel for="endereco" value="Endereço" styleClass="requerido"/>
                    <h:inputText id="endereco" value="#{inscricaoBean.candidato.endereco}" size="50"
                          styleClass="ui-inputfield" label="Endereço" maxlength="80" required="true"/>
                </h:panelGroup>
                <h:panelGroup styleClass="form-block" layout="block">
                    <h:outputLabel for="cidade" value="Cidade" styleClass="requerido"/>
                    <h:inputText id="cidade" value="#{inscricaoBean.candidato.cidade}" size="50"
                                 label="Cidade" maxlength="50" required="true"/>
                    <h:outputLabel for="estado" value="Estado" styleClass="requerido"/>
                    <h:inputText id="estado" value="#{inscricaoBean.candidato.estado}" size="2"
                                 label="Estado" maxlength="2" required="true"/>
                </h:panelGroup>
                <h:panelGroup styleClass="form-block" layout="block">
                    <h:outputLabel for="cep" value="CEP" styleClass="requerido"/>
                    <h:inputText id="cep" value="#{inscricaoBean.candidato.cep}" label="CEP" size="10" maxlength="8" required="true"/>
                    <h:outputLabel for="bairro" value="Bairro"/>
                    <h:inputText id="bairro" value="#{inscricaoBean.candidato.bairro}" size="30" label="Bairro" maxlength="50"/>
                </h:panelGroup>
                <h:panelGroup styleClass="form-block" layout="block">
                    <h:outputLabel for="fone" value="Fone"/>
                    <h:inputText id="fone" value="#{inscricaoBean.candidato.fone}" label="Fone" size="15"/>
                    <h:outputLabel for="celular" value="Celular"/>
                    <h:inputText id="celular" value="#{inscricaoBean.candidato.celular}" label="Celular" size="15"/>
                </h:panelGroup>
                <h:panelGroup styleClass="form-block" layout="block">
                    <h:outputLabel for="email" value="E-mail" styleClass="requerido"/>
                    <h:inputText id="email" value="#{inscricaoBean.candidato.email}" size="80"
                          label="E-mail" maxlength="200" required="true"/>
                </h:panelGroup>
                <h:panelGroup styleClass="form-block" layout="block">
                    <h:outputLabel for="instituicao" value="Instituição" styleClass="requerido"/>
                    <h:inputText id="instituicao" value="#{inscricaoBean.candidato.instituicao}" size="80"
                          label="Instituição" maxlength="100" required="true"/>
                </h:panelGroup>
                <h:panelGroup styleClass="form-block" layout="block">
                    <h:outputLabel for="programa" value="Programa"  styleClass="requerido"/>
                    <h:inputText id="programa" value="#{inscricaoBean.candidato.programa}" size="80"
                          label="Programa" maxlength="100" required="true"/>
                </h:panelGroup>
            </h:panelGroup>
            <div class="submit">
                <h:commandButton value="Confirmar Inscrição" action="#{inscricaoBean.confirmaAction}"/>
            </div>
            <h:messages/>
        </h:form>
    </ui:define>

</ui:composition>

src/main/webapp/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                template="/WEB-INF/templates/layout.xhtml">

    <ui:define name="styles">
        <!--<link href="#{request.contextPath}/css/inscricao.css" rel="stylesheet" type="text/css" />-->
    </ui:define>

    <ui:define name="metadata">
    </ui:define>

    <ui:define name="javascript">
    </ui:define>

    <ui:define name="content">
        <h:form>
            <div class="titulo-form">Login</div>
            <h:panelGroup style="text-align: left; margin-bottom: 10px;" layout="block">
                <h:panelGroup styleClass="form-block" layout="block">
                    <h:outputLabel for="login" value="Login"/>
                    <h:inputText id="login" value="#{loginBean.login}" label="Login" size="20" required="true"/>
                </h:panelGroup>
                <h:panelGroup styleClass="form-block" layout="block">
                    <h:outputLabel for="senha" value="Senha"/>
                    <h:inputText id="senha" value="#{loginBean.senha}" label="Senha" size="20" required="true"/>
                </h:panelGroup>
            </h:panelGroup>
            <div class="submit">
                <h:commandButton value="Login" action="#{loginBean.login}"/>
            </div>
            <h:messages/>
        </h:form>
    </ui:define>

</ui:composition>